version: "3.9"

services:
  db:
    image: postgres:15
    container_name: prisma-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sandy
      POSTGRES_DB: image_upload
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
